"""Reconcile per-repository Bronze files with the current filtered listing.

Why this exists (#216)
----------------------
A repository that is **renamed or recased** leaves its old Bronze files on
disk forever, beside the new ones. ``unb-mds/2025-1-NoFluxoUNB`` and
``unb-mds/2025-1-NoFluxoUnB`` are the same repository (id ``957040204``);
GitHub resolves names case-insensitively, so both spellings resolve to the
current one. The pipeline writes the current-case file; the old-case file
is never written again and never removed. Silver and Gold consume Bronze
per-repository files by glob, so both are read and **the repository is
counted twice in published data** (measured: commits 1,239 current +
1,219 orphan = 2,458 published).

No existing guard can see it, by construction: every assertion in this
codebase is that records must not *fall*. The orphan *adds* records, so
counts go up (suspicious to nothing), ``no-record-vanished`` sees nothing
vanished, and the registry — generated by scanning the layers — faithfully
lists the orphan as a legitimate file.

The clean fix is to key the files by repository id, which is stable across
renames and already in the payload; that is a corpus-wide rename and out
of scope here. This module is the interim reconciliation: after
extraction, a per-repository file whose repository is not in the current
filtered listing is stale, and is removed.

Deletion safety — a deletion routine is one bug away from wiping a corpus,
so every guard here REFUSES (deleting nothing) rather than guessing:

1. **The recase trap.** A case-*sensitive* compare is how the orphan
   arose, and a case-sensitive delete can remove the wrong file. A file
   whose repository matches the listing case-insensitively is an orphan
   only when the current-case file sits beside it (the rename leftover);
   when it is the *only* file for that repository it is the live data —
   the run skipped or has not yet written that family — and it is kept.
   Deleting the only copy is precisely the record loss every other guard
   in this codebase exists to prevent.
2. **An empty or unreadable listing deletes nothing.** A failed listing
   must never read as "every repository is gone".
3. **Nothing outside ``data/bronze`` is touched**, and inside it only
   direct children matching a family glob (``commits_*.json`` &c.), with
   the retired aggregates and ``_with_stats`` derived copies excluded by
   :func:`coops.bronze.files.bronze_files` — the one enumeration that
   already knows those rules.
4. **A listing not known to be COMPLETE refuses.** The guard lives in
   the FILE, not in the argv of this process, because the narrowed run
   and the reconciliation need not be the same one. Run A is a manual
   dispatch with ``--max-repos 5``: it truncates **before** the write,
   writes a 5-entry ``repositories_filtered.json`` and exits. Run B is a
   later reconciliation with a completely clean argv — no ``--max-repos``,
   no ``--repo``, no ``--offline`` — and reading that 5-entry file it
   would delete the other ~481 repositories' per-repository files. An
   argv check passes every other guard here and still wipes the corpus,
   so there is none: the producer
   (:func:`coops.bronze.repositories.extract_repositories`) writes
   ``complete: true`` into the listing's ``_metadata`` only when it
   enumerated the organisation unbounded, every narrowing path simply
   does not set it, and **absent means incomplete** — fail closed, so
   every listing already on disk refuses too. Never the size:
   ``record_count`` is computed after truncation, so it reads 5 for a
   capped run and 5 for a genuine five-repository organisation, which is
   the same defect wearing a field name. And an ``[]`` listing carries
   no ``_metadata`` at all — the most destructive possible input is the
   one with the least evidence — which refuses here before any name is
   consulted. ``repositories_raw.json`` is no fallback: the cap bounds
   the fetch, so after a capped run neither file holds the full list.

Dry run is the default of this function (``apply=False``): a library that
deletes only when the caller says so. The extraction command is opt-in the
same way — a full run REPORTS the orphans and removes nothing until
``--reconcile-apply`` is passed, because the mode you get by forgetting has
to be the safe one. Every path prints which mode ran.
"""

from __future__ import annotations

import json
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

from coops.bronze.files import BRONZE_FAMILIES, bronze_files, repo_of
from coops.utils.data_helpers import strip_metadata

#: The listing that names the repositories the current run extracts. Every
#: per-repository Bronze filename is derived from it, so it is also the only
#: legitimate answer to "which files may exist".
FILTERED_LISTING = "repositories_filtered.json"

#: Default family set, sorted for a deterministic report (see #172: two runs
#: over identical input must enumerate in the same order).
ALL_FAMILIES: tuple[str, ...] = tuple(sorted(BRONZE_FAMILIES))


@dataclass
class Reconciliation:
    """What :func:`reconcile_orphans` found and, in apply mode, what it did.

    ``refused`` is the reason string when the reconciliation refused to run
    (deleting nothing), or ``None`` when it ran. ``orphans`` lists the stale
    files it identified — deleted only when ``applied`` — and ``deleted``
    lists the ones actually removed, so a dry run can never be mistaken for
    an apply. ``kept_variants`` lists the case-variant files kept as the
    only copy for their repository (guard 1 above).
    """

    refused: str | None = None
    applied: bool = False
    orphans: list[Path] = field(default_factory=list)
    deleted: list[Path] = field(default_factory=list)
    kept_variants: list[Path] = field(default_factory=list)


def _listing_names(payload: object) -> list[str]:
    """The repository names a filtered listing carries, or [] when none.

    The ``_metadata`` first element ``save_json_data`` prepends is stripped
    by the shared helper — see the domain notes for why hand-filtering
    ``_metadata`` keys is the wrong shape. A name containing ``/`` cannot
    be a GitHub repository name and is dropped rather than spliced into a
    path: the listing is API data, and the deletion below must never be
    pointed outside ``bronze_dir`` by a corrupt entry.
    """
    if not isinstance(payload, list):
        return []
    return [
        record["name"]
        for record in strip_metadata(payload)
        if isinstance(record, dict)
        and isinstance(record.get("name"), str)
        and record["name"]
        and "/" not in record["name"]
    ]


def _listing_metadata(payload: object) -> dict | None:
    """The ``_metadata`` element ``save_json_data`` prepends, or None.

    Never reconstructed, never defaulted: a listing without provenance is
    an incomplete listing, and the caller refuses on it. An ``[]`` listing
    has none at all — ``save_json_data`` prepends the element only for
    non-empty lists.
    """
    if (
        isinstance(payload, list)
        and payload
        and isinstance(payload[0], dict)
        and "_metadata" in payload[0]
    ):
        meta = payload[0]["_metadata"]
        return meta if isinstance(meta, dict) else None
    return None


def reconcile_orphans(
    bronze_dir: Path | str,
    *,
    apply: bool = False,
    families: Iterable[str] = ALL_FAMILIES,
) -> Reconciliation:
    """Remove per-repository Bronze files for repositories the current
    filtered listing does not name.

    The listing must carry its own completeness provenance —
    ``_metadata.complete: true``, written by the producer only for an
    unbounded enumeration — or this REFUSES and deletes nothing, whatever
    the argv of the current process says (see guard 4 in the module
    docstring: the narrowed run and the reconciliation need not be the
    same process, so only the file can be trusted). With ``apply=False``
    (the default) nothing is deleted and the return value reports what a
    full run would remove.
    """
    directory = Path(bronze_dir)
    listing = directory / FILTERED_LISTING

    def refuse(reason: str) -> Reconciliation:
        print(f"Bronze reconcile: REFUSED — {reason} (nothing deleted)")
        return Reconciliation(refused=reason)

    if not directory.is_dir():
        return refuse(f"no Bronze layer at {directory} — nothing to reconcile")
    try:
        payload = json.loads(listing.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return refuse(
            f"{FILTERED_LISTING} is absent from {directory} — with no listing, "
            "every file looks stale and deleting could wipe the corpus"
        )
    except (OSError, ValueError) as exc:
        return refuse(f"{FILTERED_LISTING} cannot be read ({exc})")

    # The deletion guard, and it reads the FILE: a listing that does not
    # positively assert its own completeness may be a narrowed subset
    # (--max-repos, --repo, an offline replay) or predate the provenance,
    # and a subset is indistinguishable from "every other repository is
    # gone". `is not True` — not falsy — so a corrupt value refuses too.
    meta = _listing_metadata(payload)
    if meta is None or meta.get("complete") is not True:
        return refuse(
            f"{FILTERED_LISTING} does not assert a complete listing "
            "(_metadata.complete is absent or not true) — it may be narrowed "
            "(--repo, --max-repos, an offline replay) or predate #216, and a "
            "subset cannot be told from every other repository being gone; "
            "run a full networked listing to reconcile"
        )

    names = _listing_names(payload)
    if not names:
        return refuse(
            f"{FILTERED_LISTING} holds no repositories — a failed listing must "
            "not read as 'every repository is gone'"
        )

    exact = set(names)
    current_case: dict[str, list[str]] = {}
    for name in names:
        current_case.setdefault(name.casefold(), []).append(name)

    result = Reconciliation(applied=apply)
    for family in sorted(families):
        for path in bronze_files(directory, family):
            repo = repo_of(path, family)
            if repo in exact:
                continue  # the live file, spelled as this run writes it
            candidates = current_case.get(repo.casefold(), [])
            if not candidates:
                # The repository is absent from the listing entirely: the
                # file is stale (renamed away, deleted or excluded).
                result.orphans.append(path)
            elif any(
                (directory / f"{family}_{name}.json").is_file() for name in candidates
            ):
                # The current-case file sits beside this one: a rename or
                # recase leftover, and both are being read (#216).
                result.orphans.append(path)
            else:
                # No current-case file exists for this family — this file is
                # the only copy the corpus has (the run skipped or has not
                # yet written it), so it stays.
                result.kept_variants.append(path)

    outside = [p for p in result.orphans if p.parent != directory]
    if outside:
        return refuse(
            f"enumerated a file outside {directory} ({outside[0].name}) — "
            "refusing to delete anything"
        )

    if apply:
        for path in result.orphans:
            path.unlink()
            result.deleted.append(path)

    mode = "APPLY" if apply else "DRY RUN (nothing deleted)"
    verb = "removed" if apply else "would remove"
    print(
        f"Bronze reconcile ({mode}): {len(result.orphans)} stale file(s) {verb}, "
        f"{len(result.kept_variants)} case-variant(s) kept as the only copy "
        f"for their repository"
    )
    for path in result.orphans:
        print(f"  [{verb}: {path.name}]")
    for path in result.kept_variants:
        print(f"  [kept, only copy for a renamed repository: {path.name}]")
    return result
