/**
 * DataNotGenerated Component
 *
 * Empty state shown when a data file hasn't been generated by the pipeline
 * yet (the data source answered 404, see `DataNotFoundError`). This is the
 * normal situation right after a fork is set up or while the first pipeline
 * run is still in progress, so it is presented as information, not an error.
 */
import type { ReactNode } from 'react';

interface DataLoadErrorProps {
  message: string;
}

/** Alert for real load failures (network, HTTP 5xx, invalid JSON...). */
export function DataLoadError({ message }: DataLoadErrorProps) {
  return (
    <div
      className="bg-red-900/50 border border-red-700 text-red-300 px-4 py-3 rounded text-center"
      role="alert"
    >
      <strong className="font-bold">Error loading data: </strong>
      <span>{message}</span>
    </div>
  );
}

interface DataNotGeneratedProps {
  /** Path of the missing file relative to the data directory, e.g. 'silver/temporal_events.json'. */
  path: string;
  className?: string;
  /** Extra requirement for this particular file, shown after the generic instructions. */
  hint?: ReactNode;
}

export default function DataNotGenerated({ path, className = '', hint }: DataNotGeneratedProps) {
  const file = `data/${path}`;

  return (
    <div
      role="status"
      data-testid="data-not-generated"
      className={`border rounded-lg p-6 text-center ${className}`}
      style={{ backgroundColor: '#222222', borderColor: '#333333' }}
    >
      <h3 className="text-lg font-bold text-white mb-2">
        This data hasn&apos;t been generated yet
      </h3>
      <p className="text-slate-300 text-sm mb-2">
        The file <code className="px-1 rounded bg-slate-800 text-slate-100">{file}</code> was
        not found. The daily data pipeline creates it, so it will show up here after the next
        pipeline run finishes.
      </p>
      <p className="text-slate-400 text-sm">
        To generate it now, run the <strong>Bronze Layer - Data Extraction</strong> workflow
        (which also runs the Silver and Gold layers) from the repository&apos;s Actions tab.
      </p>
      {hint && <p className="text-slate-400 text-sm mt-2">{hint}</p>}
    </div>
  );
}
